
export const FETCH_WEATHER_DATA_REQUEST = "FETCH_WEATHER_DATA_REQUEST";
export const FETCH_WEATHER_DATA_SUCCESS = "FETCH_WEATHER_DATA_SUCCESS";
export const FETCH_WEATHER_DATA_FAILURE = "FETCH_WEATHER_DATA_FAILURE";

